/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TailwindExampleComponent {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTailwindExampleComponentElement extends Components.TailwindExampleComponent, HTMLStencilElement {
    }
    var HTMLTailwindExampleComponentElement: {
        prototype: HTMLTailwindExampleComponentElement;
        new (): HTMLTailwindExampleComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "tailwind-example-component": HTMLTailwindExampleComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TailwindExampleComponent {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "tailwind-example-component": TailwindExampleComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "tailwind-example-component": LocalJSX.TailwindExampleComponent & JSXBase.HTMLAttributes<HTMLTailwindExampleComponentElement>;
        }
    }
}
