/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LinkButtonType } from "./components/link-button/link-button";
export { LinkButtonType } from "./components/link-button/link-button";
export namespace Components {
    interface LinkButton {
        "color": LinkButtonType;
    }
}
declare global {
    interface HTMLLinkButtonElement extends Components.LinkButton, HTMLStencilElement {
    }
    var HTMLLinkButtonElement: {
        prototype: HTMLLinkButtonElement;
        new (): HTMLLinkButtonElement;
    };
    interface HTMLElementTagNameMap {
        "link-button": HTMLLinkButtonElement;
    }
}
declare namespace LocalJSX {
    interface LinkButton {
        "color"?: LinkButtonType;
    }
    interface IntrinsicElements {
        "link-button": LinkButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "link-button": LocalJSX.LinkButton & JSXBase.HTMLAttributes<HTMLLinkButtonElement>;
        }
    }
}
